#!/bin/bash
API="https://commons.wikimedia.org/w/api.php"

search() {
  local label="$1" query="$2"
  local result=$(curl -s "${API}?action=query&list=search&srsearch=$(echo "$query" | sed 's/ /+/g')&srnamespace=6&format=json&srlimit=1" | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{const j=JSON.parse(d);j.query.search.forEach(r=>console.log(r.title.replace('File:','')))})")
  echo "$label|$result"
}

search "caravaggio-bacchus" "Caravaggio Bacchus Uffizi"
search "rembrandt-bathsheba" "Rembrandt Bathsheba Her Bath 1654"
search "velazquez-old-woman-frying-eggs" "Velazquez Vieja friendo huevos"
search "velazquez-rokeby-venus" "Rokeby Venus Velazquez National Gallery"
search "rubens-descent-from-the-cross" "Rubens Descent Cross"
search "vermeer-girl-reading-letter" "Vermeer Girl Reading Letter Open Window"
search "vermeer-music-lesson" "Vermeer Music Lesson"
search "el-jaleo" "Sargent El Jaleo"
search "self-portrait-with-model" "Anders Zorn Self-portrait with model 1896"
search "omnibus-i" "Anders Zorn Omnibus"
search "our-daily-bread" "Anders Zorn daily bread"
search "girls-from-dalarna" "Anders Zorn Girls Dalarna bath"
search "the-stone-breakers" "Courbet Stone Breakers"
search "the-angelus" "Millet Angelus painting"
search "the-shepherdess" "Millet Shepherdess Flock painting"
search "reply-cossacks" "Repin Zaporozhian Cossacks"
search "unexpected-visitors" "Ilya Repin Unexpected visitors"
search "cafe-terrace-at-night" "Van Gogh Cafe Terrace Night"
search "the-card-players" "Cezanne Card Players"
search "the-large-bathers" "Cezanne Large Bathers"
search "where-do-we-come-from" "Gauguin D'ou venons nous"
search "vision-after-sermon" "Gauguin Vision Sermon Jacob Wrestling"
search "two-tahitian-women" "Gauguin Two Tahitian Women"
search "bathers-at-asnieres" "Seurat Bathers Asnieres"
search "parade-de-cirque" "Seurat Parade cirque sideshow"
search "divan-japonais" "Toulouse-Lautrec Divan Japonais poster"
search "the-toilette" "Toulouse-Lautrec La Toilette"
search "mucha-spring" "Alfons Mucha Spring 1896"
search "mucha-job" "Alfons Mucha Job"
search "mucha-zodiac" "Alfons Mucha Zodiac"
search "mucha-slav-epic" "Mucha Slav Epic"
search "mucha-evening-star" "Mucha Evening Star"
search "klimt-adele" "Klimt Portrait Adele Bloch-Bauer"
search "klimt-judith" "Klimt Judith I"
search "vrubel-demon" "Vrubel Demon Seated painting"
search "vrubel-swan" "Vrubel Swan Princess painting"
search "vrubel-pan" "Vrubel Pan painting 1899"
search "vrubel-lilacs" "Vrubel Lilacs painting"
search "beardsley-peacock" "Beardsley Peacock Skirt Salome"
search "beardsley-isolde" "Beardsley Isolde"
search "millais-blind-girl" "Millais Blind Girl painting"
search "millais-autumn-leaves" "Millais Autumn Leaves painting"
search "millais-christ-carpenter" "Millais Christ House Parents Carpenter"
search "millais-bridesmaid" "Millais Bridesmaid 1851"
search "waterhouse-circe" "Waterhouse Circe Offering Cup Ulysses"
search "waterhouse-crystal-ball" "Waterhouse Crystal Ball"
search "rossetti-beata-beatrix" "Rossetti Beata Beatrix"
search "rossetti-the-beloved" "Rossetti Beloved Bride painting"
search "hunt-awakening-conscience" "Holman Hunt Awakening Conscience"
search "hunt-isabella-basil" "Holman Hunt Isabella Pot Basil"
search "paxton-new-necklace" "William McGregor Paxton New Necklace"
search "paxton-house-maid" "William McGregor Paxton Housemaid"
search "paxton-tea-leaves" "William McGregor Paxton Tea Leaves"
search "paxton-blue-cup" "William McGregor Paxton Blue Cup"
search "paxton-nude" "William McGregor Paxton Nude"
